version: "3"
services:
 db:
   image: mysql:latest
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: METEO
     MYSQL_USER: admin
     MYSQL_PASSWORD: root
   ports:
     - "3306:3306"
   volumes:
    - /Users/samuelbouhenic/dumps/Dump20200424:/docker-entrypoint-initdb.d
   networks:
            testing_net:
                ipv4_address: 171.17.0.3
  


 web:
   image: tomcat:9.0
   # Environment variables do not appear to be getting loaded the first time Tomcat starts!
   #environment:
     #JDBC_URL: jdbc:mysql://db:3306/example_db?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
     #JDBC_USER: example_db_user
     #JDBC_PASS: example_db_pass
   ports:
    - "8081:8080"
   volumes:
    - /Users/samuelbouhenic/IdeaProjects/RESTAPI/out/artifacts/RESTAPI_war2/RESTAPI_war.war:/usr/local/tomcat/webapps/RESTAPI_war.war
  #links:
    #- db
   networks:
            testing_net:
                ipv4_address: 171.17.0.4
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 171.17.0.0/16
